export const INITIAL_CATEGORIES = [
  {
    name: '5-Sleeve Jerseys',
    slug: '5-sleeve-jerseys',
    description: 'Oversized heavy-weight streetwear 5-sleeve boxy jerseys.',
    image: '',
    isActive: true,
  },
  {
    name: 'Baggy',
    slug: 'baggy',
    description: 'Premium raw denim, vintage washed baggy & cargo jeans.',
    image: '',
    isActive: true,
  },
  {
    name: 'Full-Sleeve Stripes',
    slug: 'full-sleeve-stripes',
    description: 'Relaxed fit drop-shoulder woven & striped shirts.',
    image: '',
    isActive: true,
  },
  {
    name: 'Socks',
    slug: 'socks',
    description: 'Ribbed vintage cotton crew socks with custom jacquard logos.',
    image: '',
    isActive: true,
  },
  {
    name: 'Headwear',
    slug: 'headwear',
    description: 'Unstructured dad hats, 5-panel caps & vintage snapbacks.',
    image: '',
    isActive: true,
  },
  {
    name: 'Accessories',
    slug: 'accessories',
    description: 'Retro acetate sunglasses & anti-blue optical specs.',
    image: '',
    isActive: true,
  },
  {
    name: 'Shorts',
    slug: 'shorts',
    description: 'Oversized heavyweight streetwear shorts.',
    image: '',
    isActive: true,
  },
  {
    name: 'T-Shirts',
    slug: 't-shirts',
    description: 'Graphic tees, boxy fit streetwear t-shirts.',
    image: '',
    isActive: true,
  },
  {
    name: 'Track Pant',
    slug: 'track-pant',
    description: 'Relaxed fit heavyweight track pants & joggers.',
    image: '',
    isActive: true,
  },
];

export const INITIAL_PRODUCTS = [
  // 5-Sleeve Jerseys (6 products)
  {
    name: 'Argentina 5-Sleeve Retro Jersey',
    slug: 'argentina-5-sleeve-retro-jersey',
    category: '5-sleeve-jerseys',
    description: 'Heavyweight 280 GSM cotton knit jersey with retro blue and white stripes, embroidered vintage patch, and 5-sleeve boxy drop-shoulder cut.',
    price: 699,
    originalPrice: 1399,
    discount: 50,
    stock: 45,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White / Blue', 'Black / Cyan'],
    images: [
      'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: true,
    isNewArrival: true,
    isActive: true,
    rating: 4.9,
    reviewsCount: 38,
  },
  {
    name: 'Vault Oversized 5-Sleeve Black Jersey',
    slug: 'vault-oversized-5-sleeve-black-jersey',
    category: '5-sleeve-jerseys',
    description: 'Matte black boxy streetwear jersey with silver embroidered typography and breathable side mesh panels.',
    price: 799,
    originalPrice: 1599,
    discount: 50,
    stock: 30,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Jet Black', 'Charcoal'],
    images: [
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: true,
    isNewArrival: false,
    isActive: true,
    rating: 4.8,
    reviewsCount: 29,
  },
  {
    name: 'Brasil 98 Vintage 5-Sleeve Jersey',
    slug: 'brasil-98-vintage-5-sleeve-jersey',
    category: '5-sleeve-jerseys',
    description: 'Iconic canary yellow vintage design jersey featuring green collar accents and relaxed streetwear silhouette.',
    price: 749,
    originalPrice: 1499,
    discount: 50,
    stock: 22,
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Canary Yellow', 'Classic Green'],
    images: [
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: true,
    isNewArrival: true,
    isActive: true,
    rating: 4.9,
    reviewsCount: 42,
  },
  {
    name: 'Tokyo Cyberpunk 5-Sleeve Mesh Jersey',
    slug: 'tokyo-cyberpunk-5-sleeve-mesh-jersey',
    category: '5-sleeve-jerseys',
    description: 'Dual layer high-density mesh techwear jersey with Japanese kanji embroidery.',
    price: 899,
    originalPrice: 1799,
    discount: 50,
    stock: 18,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Neon Green / Black', 'Triple Black'],
    images: [
      'https://images.unsplash.com/photo-1562157873-818bc0726f68?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: false,
    isNewArrival: true,
    isActive: true,
    rating: 4.7,
    reviewsCount: 19,
  },
  {
    name: 'Vintage Monogram 5-Sleeve Knit Jersey',
    slug: 'vintage-monogram-5-sleeve-knit-jersey',
    category: '5-sleeve-jerseys',
    description: 'Jacquard knit monogram pattern jersey crafted from soft organic combed cotton blend.',
    price: 949,
    originalPrice: 1899,
    discount: 50,
    stock: 25,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Beige / Off-White', 'Obsidian'],
    images: [
      'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: false,
    isNewArrival: false,
    isActive: true,
    rating: 4.8,
    reviewsCount: 24,
  },
  {
    name: 'Milano Block 5-Sleeve Racing Jersey',
    slug: 'milano-block-5-sleeve-racing-jersey',
    category: '5-sleeve-jerseys',
    description: 'Motorcycle block paneling design jersey with rubberized front print badge.',
    price: 799,
    originalPrice: 1599,
    discount: 50,
    stock: 14,
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Crimson / White', 'Navy / White'],
    images: [
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: false,
    isNewArrival: false,
    isActive: true,
    rating: 4.6,
    reviewsCount: 16,
  },

  // Jeans (6 products)
  {
    name: 'Raw Acid Wash Baggy Jeans',
    slug: 'raw-acid-wash-baggy-jeans',
    category: 'baggy',
    description: '14oz heavy raw indigo denim with custom vintage acid wash treatment, wide leg opening, and embossed leather patch.',
    price: 1199,
    originalPrice: 2399,
    discount: 50,
    stock: 40,
    sizes: ['28', '30', '32', '34', '36'],
    colors: ['Acid Indigo', 'Vintage Black Wash'],
    images: [
      'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1582552938357-32b906df40cb?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: true,
    isNewArrival: true,
    isActive: true,
    rating: 4.9,
    reviewsCount: 52,
  },
  {
    name: 'Multi-Pocket Tactical Cargo Jeans',
    slug: 'multi-pocket-tactical-cargo-jeans',
    category: 'baggy',
    description: 'Relaxed fit cargo denim featuring 6 utility pockets, heavy duty antique zippers, and drawcord hem adjustments.',
    price: 1299,
    originalPrice: 2599,
    discount: 50,
    stock: 35,
    sizes: ['30', '32', '34', '36'],
    colors: ['Washed Olive', 'Jet Black'],
    images: [
      'https://images.unsplash.com/photo-1517445312882-bc9910d016b7?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: true,
    isNewArrival: false,
    isActive: true,
    rating: 4.8,
    reviewsCount: 33,
  },
  {
    name: 'Vintage Destroyed Distressed Denim',
    slug: 'vintage-destroyed-distressed-denim',
    category: 'baggy',
    description: 'Hand-distressed knee abrasions with internal mesh backing for comfortable street wear style.',
    price: 1099,
    originalPrice: 2199,
    discount: 50,
    stock: 28,
    sizes: ['28', '30', '32', '34'],
    colors: ['Light Blue Wash', 'Charcoal Tint'],
    images: [
      'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: false,
    isNewArrival: true,
    isActive: true,
    rating: 4.7,
    reviewsCount: 27,
  },
  {
    name: 'Triple Stitch Wide-Leg Carpenter Jeans',
    slug: 'triple-stitch-wide-leg-carpenter-jeans',
    category: 'baggy',
    description: 'Workwear inspired carpenter jeans with hammer loop, reinforced knee panels, and contrast triple stitching.',
    price: 1249,
    originalPrice: 2499,
    discount: 50,
    stock: 20,
    sizes: ['30', '32', '34', '36'],
    colors: ['Off-White Canvas', 'Classic Raw Blue'],
    images: [
      'https://images.unsplash.com/photo-1604176354204-9268737828e4?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: false,
    isNewArrival: false,
    isActive: true,
    rating: 4.9,
    reviewsCount: 18,
  },
  {
    name: 'Obsidian Flare Stacked Denim',
    slug: 'obsidian-flare-stacked-denim',
    category: 'baggy',
    description: 'Slender top cut with dramatic stacked ankle flares and custom branded hardware buttons.',
    price: 1399,
    originalPrice: 2799,
    discount: 50,
    stock: 15,
    sizes: ['28', '30', '32', '34'],
    colors: ['Deep Obsidian'],
    images: [
      'https://images.unsplash.com/photo-1584370848010-d7fe6bc767ec?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: true,
    isNewArrival: true,
    isActive: true,
    rating: 4.8,
    reviewsCount: 21,
  },
  {
    name: 'Heritage Straight Fit Denim',
    slug: 'heritage-straight-fit-denim',
    category: 'baggy',
    description: 'Classic 90s silhouette straight cut denim jeans designed for timeless versatility.',
    price: 999,
    originalPrice: 1999,
    discount: 50,
    stock: 50,
    sizes: ['28', '30', '32', '34', '36'],
    colors: ['Medium Wash Indigo', 'Black'],
    images: [
      'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: false,
    isNewArrival: false,
    isActive: true,
    rating: 4.6,
    reviewsCount: 31,
  },

  // Full-Sleeve Shirts (6 products)
  {
    name: 'Heavy Flannel Oversized Plaid Shirt',
    slug: 'heavy-flannel-oversized-plaid-shirt',
    category: 'full-sleeve-stripes',
    description: '320 GSM thick brush cotton flannel shirt with chest patch pockets and drop shoulder relaxed fit.',
    price: 899,
    originalPrice: 1799,
    discount: 50,
    stock: 32,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Shadow Red / Black', 'Forest Green / Navy'],
    images: [
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: true,
    isNewArrival: true,
    isActive: true,
    rating: 4.8,
    reviewsCount: 41,
  },
  {
    name: 'Vintage Corduroy Button-Down Overshirt',
    slug: 'vintage-corduroy-button-down-overshirt',
    category: 'full-sleeve-stripes',
    description: 'Soft 8-wale cotton corduroy overshirt with custom tortoiseshell buttons.',
    price: 999,
    originalPrice: 1999,
    discount: 50,
    stock: 26,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Caramel Tan', 'Washed Olive'],
    images: [
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: true,
    isNewArrival: false,
    isActive: true,
    rating: 4.9,
    reviewsCount: 36,
  },
  {
    name: 'Minimalist Cuban Collar Woven Shirt',
    slug: 'minimalist-cuban-collar-woven-shirt',
    category: 'full-sleeve-stripes',
    description: 'Sleek matte texture breathable lyocell blend long sleeve shirt with camp collar.',
    price: 849,
    originalPrice: 1699,
    discount: 50,
    stock: 19,
    sizes: ['M', 'L', 'XL'],
    colors: ['Off-White Cream', 'Pitch Black'],
    images: [
      'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: false,
    isNewArrival: true,
    isActive: true,
    rating: 4.7,
    reviewsCount: 15,
  },
  {
    name: 'Military Utility Double-Pocket Shirt',
    slug: 'military-utility-double-pocket-shirt',
    category: 'full-sleeve-stripes',
    description: 'Durable cotton ripstop weave utility shirt with functional chest pockets and sleeve loops.',
    price: 899,
    originalPrice: 1799,
    discount: 50,
    stock: 22,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Khaki Beige', 'Foliage Green'],
    images: [
      'https://images.unsplash.com/photo-1603252109303-2751441dd157?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: false,
    isNewArrival: false,
    isActive: true,
    rating: 4.8,
    reviewsCount: 22,
  },
  {
    name: 'Vault Monogram Satin Bowling Shirt',
    slug: 'vault-monogram-satin-bowling-shirt',
    category: 'full-sleeve-stripes',
    description: 'Silky smooth vintage satin feel shirt featuring tonal monogram embroidery along the hem.',
    price: 1099,
    originalPrice: 2199,
    discount: 50,
    stock: 16,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Midnight Navy', 'Emerald Green'],
    images: [
      'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: true,
    isNewArrival: true,
    isActive: true,
    rating: 4.9,
    reviewsCount: 19,
  },
  {
    name: 'Raw Linen Relaxed Resort Shirt',
    slug: 'raw-linen-relaxed-resort-shirt',
    category: 'full-sleeve-stripes',
    description: 'Lightweight pure French flax linen shirt ideal for hot summer layering.',
    price: 799,
    originalPrice: 1599,
    discount: 50,
    stock: 35,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Pure White', 'Sand Beige'],
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: false,
    isNewArrival: false,
    isActive: true,
    rating: 4.6,
    reviewsCount: 28,
  },

  // Socks (6 products)
  {
    name: 'Vintage Ribbed Crew Socks 3-Pack',
    slug: 'vintage-ribbed-crew-socks-3-pack',
    category: 'socks',
    description: 'Thick cushion sole retro ribbed crew socks engineered from 100% combed cotton with anti-odor yarn.',
    price: 399,
    originalPrice: 799,
    discount: 50,
    stock: 80,
    sizes: ['Free Size'],
    colors: ['Off-White / Black / Olive'],
    images: [
      'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: true,
    isNewArrival: true,
    isActive: true,
    rating: 4.9,
    reviewsCount: 64,
  },
  {
    name: 'Vault Monogram Jacquard Street Socks',
    slug: 'vault-monogram-jacquard-street-socks',
    category: 'socks',
    description: 'High elasticity compression ankle ribbed socks featuring high-contrast VV Monogram logo.',
    price: 299,
    originalPrice: 599,
    discount: 50,
    stock: 65,
    sizes: ['Free Size'],
    colors: ['Black / White', 'White / Red'],
    images: [
      'https://images.unsplash.com/photo-1582966772680-860e372bb558?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: false,
    isNewArrival: false,
    isActive: true,
    rating: 4.8,
    reviewsCount: 39,
  },
  {
    name: 'Flame Graphic Skater Socks',
    slug: 'flame-graphic-skater-socks',
    category: 'socks',
    description: 'Bold retro flame knitted graphic upper on reinforced toe and heel socks.',
    price: 349,
    originalPrice: 699,
    discount: 50,
    stock: 45,
    sizes: ['Free Size'],
    colors: ['Black / Yellow Flame', 'White / Crimson Flame'],
    images: [
      'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: true,
    isNewArrival: true,
    isActive: true,
    rating: 4.7,
    reviewsCount: 22,
  },
  {
    name: 'Retro Stripe Athletic Ankle Socks',
    slug: 'retro-stripe-athletic-ankle-socks',
    category: 'socks',
    description: 'Dual stripe athletic tube design featuring seamless toe closure for zero friction.',
    price: 329,
    originalPrice: 659,
    discount: 50,
    stock: 50,
    sizes: ['Free Size'],
    colors: ['Navy / Burgundy', 'White / Royal Blue'],
    images: [
      'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: false,
    isNewArrival: false,
    isActive: true,
    rating: 4.6,
    reviewsCount: 18,
  },
  {
    name: 'Minimalist Invisible No-Show Socks Pack',
    slug: 'minimalist-invisible-no-show-socks-pack',
    category: 'socks',
    description: 'Non-slip silicone heel grip invisible socks designed for low-top sneakers and loafers.',
    price: 349,
    originalPrice: 699,
    discount: 50,
    stock: 75,
    sizes: ['Free Size'],
    colors: ['Charcoal / White / Beige'],
    images: [
      'https://images.unsplash.com/photo-1582966772680-860e372bb558?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: false,
    isNewArrival: false,
    isActive: true,
    rating: 4.8,
    reviewsCount: 45,
  },
  {
    name: 'Washed Tie-Dye Heavy Crew Socks',
    slug: 'washed-tie-dye-heavy-crew-socks',
    category: 'socks',
    description: 'Hand tie-dyed organic cotton socks with extra terry loop cushioning.',
    price: 399,
    originalPrice: 799,
    discount: 50,
    stock: 30,
    sizes: ['Free Size'],
    colors: ['Ocean Blue Dye', 'Smokey Black Dye'],
    images: [
      'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: false,
    isNewArrival: true,
    isActive: true,
    rating: 4.7,
    reviewsCount: 14,
  },

  // Caps (6 products)
  {
    name: 'Vintage Distressed Wash Dad Cap',
    slug: 'vintage-distressed-wash-dad-cap',
    category: 'headwear',
    description: 'Unstructured 6-panel washed twill dad hat with vintage metal buckle strap back and subtle VV embroidery.',
    price: 499,
    originalPrice: 999,
    discount: 50,
    stock: 50,
    sizes: ['Adjustable'],
    colors: ['Washed Black', 'Faded Navy', 'Olive Green'],
    images: [
      'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: true,
    isNewArrival: true,
    isActive: true,
    rating: 4.9,
    reviewsCount: 58,
  },
  {
    name: 'Streetwear 5-Panel Camp Cap',
    slug: 'streetwear-5-panel-camp-cap',
    category: 'headwear',
    description: 'Flat visor 5-panel cap made from water-resistant nylon fabric with reflective logo front patch.',
    price: 549,
    originalPrice: 1099,
    discount: 50,
    stock: 38,
    sizes: ['Adjustable'],
    colors: ['Stealth Black', 'Desert Camo'],
    images: [
      'https://images.unsplash.com/photo-1575428652377-a2d80e2277fc?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: true,
    isNewArrival: false,
    isActive: true,
    rating: 4.8,
    reviewsCount: 31,
  },
  {
    name: 'Retro Trucker Mesh Snapback',
    slug: 'retro-trucker-mesh-snapback',
    category: 'headwear',
    description: 'Classic foam front trucker hat with mesh ventilation panels and 3D foam puff print graphic.',
    price: 449,
    originalPrice: 899,
    discount: 50,
    stock: 42,
    sizes: ['Adjustable'],
    colors: ['Black / White Mesh', 'Brown / Cream'],
    images: [
      'https://images.unsplash.com/photo-1534215754734-18e55d13e346?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: false,
    isNewArrival: true,
    isActive: true,
    rating: 4.7,
    reviewsCount: 29,
  },
  {
    name: 'Minimalist Corduroy Snapback',
    slug: 'minimalist-corduroy-snapback',
    category: 'headwear',
    description: 'Thick wale corduroy structured crown cap with flat brim and brass eyelets.',
    price: 599,
    originalPrice: 1199,
    discount: 50,
    stock: 24,
    sizes: ['Adjustable'],
    colors: ['Chocolate Brown', 'Mustard Yellow'],
    images: [
      'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: false,
    isNewArrival: false,
    isActive: true,
    rating: 4.9,
    reviewsCount: 20,
  },
  {
    name: 'Heavy Knit Ribbed Beanie',
    slug: 'heavy-knit-ribbed-beanie',
    category: 'headwear',
    description: 'Double layer soft acrylic knit beanie featuring a turn-up cuff and woven branded flag label.',
    price: 399,
    originalPrice: 799,
    discount: 50,
    stock: 60,
    sizes: ['Free Size'],
    colors: ['Jet Black', 'Heather Gray', 'Rust Orange'],
    images: [
      'https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: true,
    isNewArrival: true,
    isActive: true,
    rating: 4.8,
    reviewsCount: 47,
  },
  {
    name: 'Vintage Racing Embroidery Baseball Cap',
    slug: 'vintage-racing-embroidery-baseball-cap',
    category: 'caps',
    description: 'Motor-racing inspired multi-color embroidery cap with contrast sandwich brim.',
    price: 599,
    originalPrice: 1199,
    discount: 50,
    stock: 20,
    sizes: ['Adjustable'],
    colors: ['Red / Off-White', 'Black / Yellow'],
    images: [
      'https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: false,
    isNewArrival: false,
    isActive: true,
    rating: 4.6,
    reviewsCount: 16,
  },

  // Glasses (6 products)
  {
    name: 'Cyber Vintage Acetate Sunglasses',
    slug: 'cyber-vintage-acetate-sunglasses',
    category: 'accessories',
    description: 'Thick handcrafted acetate rectangular frame with UV400 dark tint lenses and gold metal temple rivets.',
    price: 899,
    originalPrice: 1799,
    discount: 50,
    stock: 35,
    sizes: ['Standard'],
    colors: ['Glossy Black', 'Tortoiseshell'],
    images: [
      'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: true,
    isNewArrival: true,
    isActive: true,
    rating: 4.9,
    reviewsCount: 48,
  },
  {
    name: 'Retro Oval Metal Frame Specs',
    slug: 'retro-oval-metal-frame-specs',
    category: 'accessories',
    description: 'Ultra-lightweight stainless steel slim oval frame with clear blue-light filtering lenses.',
    price: 799,
    originalPrice: 1599,
    discount: 50,
    stock: 28,
    sizes: ['Standard'],
    colors: ['Gold / Clear', 'Silver / Tinted'],
    images: [
      'https://images.unsplash.com/photo-1574258495973-f010dfbb5371?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: true,
    isNewArrival: false,
    isActive: true,
    rating: 4.8,
    reviewsCount: 37,
  },
  {
    name: 'Y2K Frameless Shield Sunglasses',
    slug: 'y2k-frameless-shield-sunglasses',
    category: 'accessories',
    description: 'Futuristic wide wrap-around rimless shield lenses with chrome arm detailing.',
    price: 949,
    originalPrice: 1899,
    discount: 50,
    stock: 22,
    sizes: ['Standard'],
    colors: ['Silver Chrome', 'Smokey Black'],
    images: [
      'https://images.unsplash.com/photo-1508296695146-257a814070b4?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: false,
    isNewArrival: true,
    isActive: true,
    rating: 4.7,
    reviewsCount: 23,
  },
  {
    name: 'Classic Wayfarer Polarized Shades',
    slug: 'classic-wayfarer-polarized-shades',
    category: 'accessories',
    description: 'Iconic shape polarized lenses offering 100% UVA/UVB protection with matte rubber finish frames.',
    price: 849,
    originalPrice: 1699,
    discount: 50,
    stock: 40,
    sizes: ['Standard'],
    colors: ['Matte Black', 'Frosted Gray'],
    images: [
      'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: false,
    isNewArrival: false,
    isActive: true,
    rating: 4.9,
    reviewsCount: 51,
  },
  {
    name: 'Hexagonal Geometric Clear Specs',
    slug: 'hexagonal-geometric-clear-specs',
    category: 'accessories',
    description: 'Sharp modern hexagonal lens outline with adjustable silicone nose pads for all day comfort.',
    price: 749,
    originalPrice: 1499,
    discount: 50,
    stock: 30,
    sizes: ['Standard'],
    colors: ['Gunmetal Gray', 'Rose Gold'],
    images: [
      'https://images.unsplash.com/photo-1574258495973-f010dfbb5371?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: true,
    isNewArrival: true,
    isActive: true,
    rating: 4.8,
    reviewsCount: 19,
  },
  {
    name: 'Vintage Aviator Gradient Sunglasses',
    slug: 'vintage-aviator-gradient-sunglasses',
    category: 'glasses',
    description: 'Double bridge pilot frame featuring warm amber gradient tint shatterproof polycarbonate lenses.',
    price: 899,
    originalPrice: 1799,
    discount: 50,
    stock: 25,
    sizes: ['Standard'],
    colors: ['Gold / Amber Gradient', 'Black / Dark Green'],
    images: [
      'https://images.unsplash.com/photo-1508296695146-257a814070b4?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: false,
    isNewArrival: false,
    isActive: true,
    rating: 4.7,
    reviewsCount: 26,
  },
];
